export const SAVE_INGREDIENTS: "FETCH_INGREDIENTS" = "FETCH_INGREDIENTS";
export const SAVE_SELECTED_INGREDIENT: "SAVE_SELECTED_INGREDIENT" =
  "SAVE_SELECTED_INGREDIENT";
export const RESET_SELECTED_INGREDIENT: "RESET_SELECTED_INGREDIENT" =
  "RESET_SELECTED_INGREDIENT";
export const SAVE_CONSTRUCTOR_BUN: "SAVE_SELECTED_BUN" = "SAVE_SELECTED_BUN";
export const SAVE_CONSTRUCTOR_INGREDIENT: "SAVE_CONSTRUCTOR_INGREDIENT" =
  "SAVE_CONSTRUCTOR_INGREDIENT";
export const REORDER_CONSTRUCTOR_INGREDIENTS: "REORDER_CONSTRUCTOR_INGREDIENTS" =
  "REORDER_CONSTRUCTOR_INGREDIENTS";
export const RESET_CONSTRUCTOR_INGREDIENTS: "RESET_CONSTRUCTOR_INGREDIENTS" =
  "RESET_CONSTRUCTOR_INGREDIENTS";
export const DELETE_CONSTRUCTOR_INGREDIENT: "DELETE_CONSTRUCTOR_INGREDIENT" =
  "DELETE_CONSTRUCTOR_INGREDIENT";
