export const WS_FEED_CONNECTION_START: "WS_FEED_CONNECTION_START" =
  "WS_FEED_CONNECTION_START";
export const WS_FEED_CONNECTION_SUCCESS: "WS_FEED_CONNECTION_SUCCESS" =
  "WS_FEED_CONNECTION_SUCCESS";
export const WS_FEED_CONNECTION_ERROR: "WS_FEED_CONNECTION_ERROR" =
  "WS_FEED_CONNECTION_ERROR";
export const WS_FEED_CONNECTION_CLOSED: "WS_FEED_CONNECTION_CLOSED" =
  "WS_FEED_CONNECTION_CLOSED";
export const WS_FEED_GET_MESSAGE: "WS_FEED_GET_MESSAGE" = "WS_FEED_GET_MESSAGE";
export const WS_FEED_SEND_MESSAGE: "WS_FEED_SEND_MESSAGE" =
  "WS_FEED_SEND_MESSAGE";

export interface IWSPublicFeedAction {
  wsStart: typeof WS_FEED_CONNECTION_START;
  wsSuccess: typeof WS_FEED_CONNECTION_SUCCESS;
  wsError: typeof WS_FEED_CONNECTION_ERROR;
  wsClosed: typeof WS_FEED_CONNECTION_CLOSED;
  wsGetMessage: typeof WS_FEED_GET_MESSAGE;
  wsSendMessage: typeof WS_FEED_SEND_MESSAGE;
}

export const wsPublicFeedAction: IWSPublicFeedAction = {
  wsStart: WS_FEED_CONNECTION_START,
  wsSuccess: WS_FEED_CONNECTION_SUCCESS,
  wsError: WS_FEED_CONNECTION_ERROR,
  wsClosed: WS_FEED_CONNECTION_CLOSED,
  wsGetMessage: WS_FEED_GET_MESSAGE,
  wsSendMessage: WS_FEED_SEND_MESSAGE,
};
