export const WS_USER_ORDERS_CONNECTION_START: "WS_USER_ORDERS_CONNECTION_START" =
  "WS_USER_ORDERS_CONNECTION_START";
export const WS_USER_ORDERS_CONNECTION_SUCCESS: "WS_USER_ORDERS_CONNECTION_SUCCESS" =
  "WS_USER_ORDERS_CONNECTION_SUCCESS";
export const WS_USER_ORDERS_CONNECTION_ERROR: "WS_USER_ORDERS_CONNECTION_ERROR" =
  "WS_USER_ORDERS_CONNECTION_ERROR";
export const WS_USER_ORDERS_CONNECTION_CLOSED: "WS_USER_ORDERS_CONNECTION_CLOSED" =
  "WS_USER_ORDERS_CONNECTION_CLOSED";
export const WS_USER_ORDERS_GET_MESSAGE: "WS_USER_ORDERS_GET_MESSAGE" =
  "WS_USER_ORDERS_GET_MESSAGE";
export const WS_USER_ORDERS_SEND_MESSAGE: "WS_USER_ORDERS_SEND_MESSAGE" =
  "WS_USER_ORDERS_SEND_MESSAGE";

export interface IWSUserOrdersActions {
  readonly WSStart: typeof WS_USER_ORDERS_CONNECTION_START;
  readonly WSSuccess: typeof WS_USER_ORDERS_CONNECTION_SUCCESS;
  readonly WSError: typeof WS_USER_ORDERS_CONNECTION_ERROR;
  readonly WSClosed: typeof WS_USER_ORDERS_CONNECTION_CLOSED;
  readonly WSGetMessage: typeof WS_USER_ORDERS_GET_MESSAGE;
  readonly WSSendMessage: typeof WS_USER_ORDERS_SEND_MESSAGE;
}

export const WSUserOrdersActions: IWSUserOrdersActions = {
  WSStart: WS_USER_ORDERS_CONNECTION_START,
  WSSuccess: WS_USER_ORDERS_CONNECTION_SUCCESS,
  WSError: WS_USER_ORDERS_CONNECTION_ERROR,
  WSClosed: WS_USER_ORDERS_CONNECTION_CLOSED,
  WSGetMessage: WS_USER_ORDERS_GET_MESSAGE,
  WSSendMessage: WS_USER_ORDERS_SEND_MESSAGE,
};
